-- Generated by mods/survivors-song/tools/generate_journal_core.py; do not edit.
-- Source: Personal Journal 1.3.3-release
-- Repository: https://github.com/Kinkairy/Project-Zomboid-Personal-Journal
-- Git commit: 718e68cde288d8e1c6eddda501b83f083f723392
-- Copyright (c) 2026 Kinkairy; MIT License, see JOURNAL-LICENSE.txt.
-- Source file: workshop/Contents/mods/LegacyJournal/42.20/media/lua/server/legacyjournal/legacyjournal_server.lua
-- Source SHA-256: 77c1236f5d16360079eec6b88ddcdd4b365091d931d0475ae20ff6128aeed777
-- Source file: workshop/Contents/mods/LegacyJournal/42.20/media/lua/client/legacyjournal/legacyjournal_client.lua
-- Source SHA-256: 0803bd762c6cdf327d7f94422b1d0e19fdee460fdc19958e8ecf90eeee1c5614

-- Selected upstream functions are copied verbatim; no event/UI registration.
-- The caller supplies the isolated LJ adapter (MODULE and getActionActorKey).
-- PZ auto-loading publishes SurvivorsSong.newJournalSync; Lua also receives the factory.
local function create(LJ)
local SYNC_CHUNK_SIZE = 50

local function sendResult(player, command, args, recipientKey)
    args.onlineID = player:getOnlineID()
    args.recipientKey = recipientKey
    sendServerCommand(player, LJ.MODULE, command, args)
end

local function slice(values, firstIndex, lastIndex)
    local result = {}
    for index = firstIndex, math.min(lastIndex, #values) do
        table.insert(result, values[index])
    end
    return result
end

local function sendReadFields(player, fields, recipientKey)
    if not sendServerCommand or not player then return end
    fields = fields or { recipes = {}, mediaLines = {} }
    local recipes = fields.recipes or {}
    local mediaLines = fields.mediaLines or {}
    local count = math.max(#recipes, #mediaLines)

    if count == 0 then
        sendResult(player, "readFields", {
            final = true,
            skillBooks = fields.skillBooks,
            skillBookStates = fields.skillBookStates,
            hasExactSkillBookSnapshot = fields.hasExactSkillBookSnapshot == true,
        }, recipientKey)
        return
    end

    for firstIndex = 1, count, SYNC_CHUNK_SIZE do
        local lastIndex = firstIndex + SYNC_CHUNK_SIZE - 1
        local final = lastIndex >= count
        sendResult(player, "readFields", {
            recipes = slice(recipes, firstIndex, lastIndex),
            mediaLines = slice(mediaLines, firstIndex, lastIndex),
            final = final,
            skillBooks = final and fields.skillBooks or nil,
            skillBookStates = final and fields.skillBookStates or nil,
            hasExactSkillBookSnapshot = final
                and fields.hasExactSkillBookSnapshot == true or false,
        }, recipientKey)
    end
end


local function getResultPlayer(args, requireRecipientKey)
    if type(args) ~= "table" then return nil end
    local onlineID = tonumber(args.onlineID)
    if not onlineID or onlineID < 0 or onlineID ~= math.floor(onlineID) then return nil end
    local player = getPlayerByOnlineID(onlineID)
    if player and player:isLocalPlayer() and not player:isDead()
        and (not requireRecipientKey
            or args.recipientKey == LJ.getActionActorKey(player)) then return player end
    return nil
end

local function applyReadFieldChunk(args)
    local player = getResultPlayer(args, true)
    if not player or not args then return end

    for _, recipeName in ipairs(args.recipes or {}) do
        player:learnRecipe(recipeName)
    end
    for _, guid in ipairs(args.mediaLines or {}) do
        if not player:isKnownMediaLine(guid) then
            player:addKnownMediaLine(guid)
        end
    end

    if args.final == true then
        local savedBooks = LJ.decodeSkills(args.skillBooks or "")
        local savedBookStates = LJ.decodeSkillBookStates(args.skillBookStates or "")
        LJ.applySkillBookProgress(player, savedBooks, savedBookStates,
            args.hasExactSkillBookSnapshot == true)
        if sendSyncPlayerFields then
            -- Vanilla book reading uses this exact field mask for recipes,
            -- read-page state, and the active skill-book multiplier.
            sendSyncPlayerFields(player, 0x00000007)
        end
    end
end

return {
    sendReadFields = sendReadFields,
    applyReadFieldChunk = applyReadFieldChunk,
}
end

SurvivorsSong = SurvivorsSong or {}
SurvivorsSong.newJournalSync = create
return create
