-- Generated by mods/survivors-song/tools/generate_journal_core.py; do not edit.
-- Source: Personal Journal 1.3.3-release
-- Repository: https://github.com/Kinkairy/Project-Zomboid-Personal-Journal
-- Git commit: 718e68cde288d8e1c6eddda501b83f083f723392
-- Copyright (c) 2026 Kinkairy; MIT License, see JOURNAL-LICENSE.txt.
-- Source file: workshop/Contents/mods/LegacyJournal/42.20/media/lua/shared/legacyjournal/legacyjournal_shared.lua
-- Source SHA-256: d054473dfac14b1eb5319746992c461f7286f42cbdd7235c5803d1c7ea9f1d89

-- The shared body is verbatim; namespace/load-log wrapping is replaced.
-- Optional nativeOverrides.sendSyncPlayerFields shadows only this instance's native call.
-- PZ auto-loading publishes SurvivorsSong.newJournalCore; Lua also receives the factory.
local function create(nativeOverrides)
local LJ = {}
local sendSyncPlayerFields = nativeOverrides and nativeOverrides.sendSyncPlayerFields or sendSyncPlayerFields

-- Rebuild this runtime index after a Lua hot reload.
LJ._permanentRewardMedia = nil

LJ.VERSION = 6
LJ.BUILD = "1.3.3-release"
LJ.MODULE = "LegacyJournal"
LJ.MAX_READ_STATUS_ITEMS = 16
LJ.WRITE_TEXT_KEY = "ContextMenu_LegacyJournal_Write"
LJ.NAME_TEXT_KEY = "IGUI_LegacyJournal_Name"
LJ.RECORDED_AT_TEXT_KEY = "IGUI_LegacyJournal_RecordedAt"
LJ.FIXED_TEST_ACTION_TIME = nil
LJ.DEFAULT_ACTION_PROGRESS_PAGES = 1
LJ.ACTION_PAGE_RATE_NUMERATOR = 7
LJ.ACTION_PAGE_RATE_DENOMINATOR = 1000
LJ.ACTION_PROGRESS_MODEL_VERSION = 2

LJ.VALID_TYPES = {
    ["Base.Diary1"] = true,
    ["Base.Diary2"] = true,
}

-- Only original permanent rewards belong in a journal. Mixed media is kept
-- when at least one line grants skill XP or teaches a recipe.
local PERMANENT_MEDIA_CODES = {
    AIM = true,
    BAA = true,
    BLA = true,
    BUA = true,
    BUT = true,
    CMB = true,
    COO = true,
    CRP = true,
    CRV = true,
    DOC = true,
    ELC = true,
    FIS = true,
    FKN = true,
    FOR = true,
    FRM = true,
    GLA = true,
    HUS = true,
    LBA = true,
    LFT = true,
    MAS = true,
    MEC = true,
    MTL = true,
    NIM = true,
    POT = true,
    RCP = true,
    REL = true,
    SBA = true,
    SBU = true,
    SNE = true,
    SPE = true,
    SPR = true,
    TAI = true,
    TRA = true,
    TRK = true,
}

-- Content weights are converted to pages before vanilla per-page timing.
LJ.WRITE_BASE = 600
LJ.WRITE_PER_CHANGED_SKILL = 120
LJ.WRITE_PER_100_XP = 1
LJ.WRITE_PER_NEW_RECIPE = 90
LJ.WRITE_PER_SKILL_BOOK = 100
LJ.WRITE_PER_VHS_LINE = 8
LJ.READ_BASE = 900
LJ.READ_PER_CHANGED_SKILL = 90
LJ.READ_PER_100_XP = 0.8
LJ.READ_PER_NEW_RECIPE = 75
LJ.READ_PER_SKILL_BOOK = 85
LJ.READ_PER_VHS_LINE = 6
local function clamp(value, minValue, maxValue)
    if value < minValue then return minValue end
    if value > maxValue then return maxValue end
    return value
end

local function safeString(value)
    if value == nil then return "" end
    return tostring(value)
end

function LJ.getGameDateTimeStamp()
    local gameTime = getGameTime and getGameTime() or nil
    if not gameTime then return nil end

    local timeOfDay = tonumber(gameTime:getTimeOfDay()) or 0
    local totalMinutes = math.floor((timeOfDay * 60) + 0.0001) % 1440
    local hour = math.floor(totalMinutes / 60)
    local minute = totalMinutes % 60
    return string.format("%04d/%02d/%02d %02d:%02d",
        tonumber(gameTime:getYear()) or 0,
        (tonumber(gameTime:getMonth()) or 0) + 1,
        (tonumber(gameTime:getDay()) or 0) + 1,
        hour,
        minute)
end

function LJ.getJournalTooltip(item)
    if not LJ.isWritten(item) then return nil end
    local md = item:getModData()
    local writtenAt = tostring(md.LJ_writtenAt or "")
    if writtenAt == "" then return nil end
    return getText(LJ.RECORDED_AT_TEXT_KEY, writtenAt)
end

function LJ.isOptionEnabled(optionName)
    local ok, enabled = pcall(function()
        local options = getSandboxOptions()
        local option = options and options:getOptionByName("LegacyJournal." .. optionName)
        if not option then return true end
        return option:getValue()
    end)

    if not ok or enabled == nil then return true end
    return enabled == true or tostring(enabled) == "true"
end

function LJ.getOptionNumber(optionName, defaultValue, minValue, maxValue)
    local value = defaultValue
    local ok, configured = pcall(function()
        local options = getSandboxOptions()
        local option = options and options:getOptionByName("LegacyJournal." .. optionName)
        return option and option:getValue() or nil
    end)
    if ok and tonumber(configured) then value = tonumber(configured) end
    if minValue ~= nil then value = math.max(value, minValue) end
    if maxValue ~= nil then value = math.min(value, maxValue) end
    return value
end

function LJ.isSkillXpEnabled()
    return LJ.isOptionEnabled("SkillXP")
end

function LJ.isRecipesEnabled()
    return LJ.isOptionEnabled("KnownRecipes")
end

function LJ.isSkillBooksEnabled()
    return LJ.isOptionEnabled("SkillBooks")
end

function LJ.isTrainingMediaEnabled()
    return LJ.isOptionEnabled("TrainingMedia")
end

function LJ.getRecoveryRatio()
    return LJ.getOptionNumber("RecoveryPercent", 100, 50, 100) / 100
end

function LJ.getActionTimeMultiplier(action, player)
    local optionName = action == "read" and "ReadTimeMultiplier" or "WriteTimeMultiplier"
    local multiplier = LJ.getOptionNumber(optionName, 1.0, 0.1, 10.0)
    return math.max(0.01, multiplier)
end

function LJ.getRecoverableSkillXp(savedXp)
    return math.floor(math.max(0, tonumber(savedXp or 0) or 0)
        * LJ.getRecoveryRatio() * 1000 + 0.5) / 1000
end

function LJ.isSupportedItem(item)
    if not item then return false end

    -- ISToolTipInv also renders fluid/resource objects in B42. Guard with
    -- the same runtime type check used by vanilla before calling item APIs.
    if type(instanceof) == "function" then
        if not instanceof(item, "InventoryItem") then return false end
        local fullType = item:getFullType()
        return fullType and LJ.VALID_TYPES[fullType] == true
    end

    -- Offline Lua harnesses do not provide PZ's global instanceof().
    local ok, fullType = pcall(function() return item:getFullType() end)
    return ok and fullType and LJ.VALID_TYPES[fullType] == true
end

function LJ.hasWritingTool(player)
    if not player then return false end
    local inventory = player:getInventory()
    if not inventory then return false end

    local ok, result = pcall(function()
        return inventory:containsTagRecurse(ItemTag.WRITE)
            or inventory:containsTagRecurse(ItemTag.BLUE_PEN)
            or inventory:containsTagRecurse(ItemTag.PEN)
            or inventory:containsTagRecurse(ItemTag.PENCIL)
            or inventory:containsTagRecurse(ItemTag.RED_PEN)
            or inventory:containsTagRecurse(ItemTag.GREEN_PEN)
    end)
    if ok and result then return true end

    local fallbackTypes = { "Pen", "Pencil", "BluePen", "RedPen", "BlackPen" }
    for _, itemType in ipairs(fallbackTypes) do
        local foundOk, found = pcall(function()
            return inventory:containsTypeRecurse(itemType)
        end)
        if foundOk and found then return true end
    end
    return false
end

function LJ.getCharacterIdentity(player)
    local result = { name = "", username = "", descId = "" }
    if not player then return result end

    local okDesc, desc = pcall(function() return player:getDescriptor() end)
    if not okDesc then desc = nil end
    if desc then
        local first = safeString(desc:getForename())
        local last = safeString(desc:getSurname())
        if first ~= "" and last ~= "" then
            result.name = first .. " " .. last
        elseif first ~= "" then
            result.name = first
        elseif last ~= "" then
            result.name = last
        end

        local okId, descId = pcall(function() return desc:getID() end)
        if okId and descId ~= nil then result.descId = tostring(descId) end
    end

    local okUser, username = pcall(function() return player:getUsername() end)
    if okUser and username then result.username = tostring(username) end

    if result.name == "" then
        local okDisplay, displayName = pcall(function() return player:getDisplayName() end)
        if okDisplay and displayName and tostring(displayName) ~= "" then
            result.name = tostring(displayName)
        elseif result.username ~= "" then
            result.name = result.username
        else
            result.name = "Unknown"
        end
    end
    return result
end

function LJ.isWritten(item)
    if not LJ.isSupportedItem(item) then return false end
    local md = item:getModData()
    return md and md.LJ_written == true
end

local function parseRecordVersion(value)
    if type(value) == "number" then
        if value == math.floor(value) then return value end
        return nil
    end
    if type(value) == "string" and string.match(value, "^%d+$") then
        return tonumber(value)
    end
    return nil
end

function LJ.getRecordVersion(item)
    if not LJ.isWritten(item) then return nil, false end
    local rawVersion = item:getModData().LJ_version
    local version = parseRecordVersion(rawVersion)
    return version, version == LJ.VERSION
end

function LJ.isSupportedRecord(item)
    local _, supported = LJ.getRecordVersion(item)
    return supported == true
end

function LJ.migrateRecord(item)
    local _, supported = LJ.getRecordVersion(item)
    return supported == true
end

function LJ.isAuthor(player, item)
    if not player or not LJ.isWritten(item) or not LJ.isSupportedRecord(item) then
        return false
    end
    local md = item:getModData()
    local identity = LJ.getCharacterIdentity(player)
    local authorUser = tostring(md.LJ_authorUser or "")
    if authorUser ~= "" and identity.username ~= "" then
        return authorUser == identity.username
    end
    return tostring(md.LJ_authorName or "") == identity.name
end

function LJ.canCurrentCharacterUpdate(player, item)
    if not LJ.isSupportedItem(item) then return false end
    if not LJ.isWritten(item) then return true end
    return LJ.isAuthor(player, item)
end

function LJ.getJournalName(item)
    if not LJ.isWritten(item) then return nil end
    local authorName = tostring(item:getModData().LJ_authorName or "")
    if authorName == "" then return nil end
    local ok, translated = pcall(function()
        return getText(LJ.NAME_TEXT_KEY, authorName)
    end)
    if ok and translated and tostring(translated) ~= LJ.NAME_TEXT_KEY then
        return tostring(translated)
    end
    return authorName .. "'s Journal"
end

function LJ.refreshJournalPresentation(item)
    if not LJ.isWritten(item) then return false end
    local changed = false
    local expectedName = LJ.getJournalName(item)
    if expectedName then
        if item:getName() ~= expectedName then
            item:setName(expectedName)
            changed = true
        end

        local ok, customName = pcall(function() return item:isCustomName() end)
        if not ok or customName ~= true then
            item:setCustomName(true)
            changed = true
        end
    end

    local authorUser = tostring(item:getModData().LJ_authorUser or "")
    if authorUser ~= "" and item:getLockedBy() ~= authorUser then
        item:setLockedBy(authorUser)
        changed = true
    end
    return changed
end

function LJ.encodeSkills(skills)
    local keys = {}
    for perkId, xp in pairs(skills or {}) do
        if perkId and xp and tonumber(xp) and tonumber(xp) > 0 then
            table.insert(keys, tostring(perkId))
        end
    end
    table.sort(keys)
    local parts = {}
    for _, perkId in ipairs(keys) do
        table.insert(parts, perkId .. "=" .. tostring(skills[perkId]))
    end
    return table.concat(parts, ";")
end

function LJ.decodeSkills(encoded)
    local result = {}
    if not encoded or encoded == "" then return result end
    for token in string.gmatch(tostring(encoded), "[^;]+") do
        local eq = string.find(token, "=", 1, true)
        if eq then
            local key = string.sub(token, 1, eq - 1)
            local value = tonumber(string.sub(token, eq + 1))
            if key ~= "" and value and value > 0 then result[key] = value end
        end
    end
    return result
end

local function isFiniteNumber(value)
    value = tonumber(value)
    return value ~= nil and value == value
        and value ~= math.huge and value ~= -math.huge
end

local function normalizeStoredSkillXp(value)
    local number = tonumber(value)
    if not isFiniteNumber(number) then return 0 end
    return math.floor(math.max(0, number) * 1000 + 0.5) / 1000
end

local function normalizeStoredSkillBookMultiplier(value)
    local number = tonumber(value)
    if not isFiniteNumber(number) then return 0 end
    return tonumber(string.format("%.9g", number)) or 0
end

local function getPerkId(perk)
    if not perk then return nil end
    local ok, perkId = pcall(function() return perk:getId() end)
    if not ok or perkId == nil then perkId = perk.id end
    if perkId == nil or tostring(perkId) == "" then return nil end
    return tostring(perkId)
end

function LJ.encodeSkillBookStates(states)
    local keys = {}
    for fullType, state in pairs(states or {}) do
        if state and tostring(fullType) ~= "" then table.insert(keys, tostring(fullType)) end
    end
    table.sort(keys)

    local lines = {}
    for _, fullType in ipairs(keys) do
        local state = states[fullType]
        local perkId = state and tostring(state.perkId or "") or ""
        local multiplier = state and tonumber(state.multiplier) or nil
        local minLevel = state and tonumber(state.minLevel) or nil
        local maxLevel = state and tonumber(state.maxLevel) or nil
        if not string.find(fullType, "[\t\r\n]")
            and perkId ~= "" and not string.find(perkId, "[\t\r\n]")
            and isFiniteNumber(multiplier) and multiplier > 0
            and isFiniteNumber(minLevel) and minLevel == math.floor(minLevel)
            and isFiniteNumber(maxLevel) and maxLevel == math.floor(maxLevel)
            and minLevel <= maxLevel then
            table.insert(lines, table.concat({
                fullType,
                perkId,
                string.format("%.9g", multiplier),
                tostring(minLevel),
                tostring(maxLevel),
            }, "\t"))
        end
    end
    return table.concat(lines, "\n")
end

function LJ.decodeSkillBookStates(encoded)
    local result = {}
    if encoded == nil or tostring(encoded) == "" then return result end
    for line in string.gmatch(tostring(encoded), "[^\n]+") do
        local fullType, perkId, multiplierText, minText, maxText =
            string.match(line, "^([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)\t([^\t]+)$")
        local multiplier = tonumber(multiplierText)
        local minLevel = tonumber(minText)
        local maxLevel = tonumber(maxText)
        if fullType and perkId and isFiniteNumber(multiplier) and multiplier > 0
            and isFiniteNumber(minLevel) and minLevel == math.floor(minLevel)
            and isFiniteNumber(maxLevel) and maxLevel == math.floor(maxLevel)
            and minLevel <= maxLevel then
            result[fullType] = {
                fullType = fullType,
                perkId = perkId,
                multiplier = multiplier,
                minLevel = minLevel,
                maxLevel = maxLevel,
            }
        end
    end
    return result
end

function LJ.encodeRecipes(recipes)
    local names = {}
    for recipeName, known in pairs(recipes or {}) do
        if known and recipeName and tostring(recipeName) ~= "" then
            table.insert(names, tostring(recipeName))
        end
    end
    table.sort(names)
    return table.concat(names, "\n")
end

function LJ.decodeRecipes(encoded)
    local result = {}
    if not encoded or encoded == "" then return result end
    for line in string.gmatch(tostring(encoded), "[^\n]+") do
        if line ~= "" then result[line] = true end
    end
    return result
end

function LJ.captureSkills(player)
    local result = {}
    if not player then return result end
    local xpObject = player:getXp()
    if not xpObject then return result end

    local maxIndex = PerkFactory.Perks.getMaxIndex()
    for index = 0, maxIndex - 1 do
        local perk = PerkFactory.Perks.fromIndex(index)
        if perk and perk ~= PerkFactory.Perks.None then
            local okId, perkId = pcall(function() return perk:getId() end)
            if okId and perkId and tostring(perkId) ~= "" then
                local okXp, xp = pcall(function() return xpObject:getXP(perk) end)
                local effectiveXp = okXp and tonumber(xp) or 0
                local level = tonumber(player:getPerkLevel(perk) or 0) or 0
                if level > 0 then
                    local okLevelXp, levelXp = pcall(function()
                        return PerkFactory.getPerk(perk):getTotalXpForLevel(level)
                    end)
                    if okLevelXp and tonumber(levelXp) then
                        effectiveXp = math.max(effectiveXp, tonumber(levelXp))
                    end
                end
                if effectiveXp > 0 then
                    result[tostring(perkId)] = effectiveXp
                end
            end
        end
    end
    return result
end

function LJ.captureRecipes(player)
    local result = {}
    if not player then return result end
    local recipes = player:getKnownRecipes()
    if not recipes then return result end
    for index = 0, recipes:size() - 1 do
        local recipeName = recipes:get(index)
        if recipeName and tostring(recipeName) ~= "" then result[tostring(recipeName)] = true end
    end
    return result
end

local function getSkillBookData(scriptItem)
    if not scriptItem or not SkillBook then return nil end
    local ok, skillName = pcall(function() return scriptItem:getSkillTrained() end)
    if not ok or not skillName or not SkillBook[skillName] then return nil end
    local okPages, pages = pcall(function() return scriptItem:getNumberOfPages() end)
    if not okPages or not pages or tonumber(pages) <= 0 then return nil end
    return SkillBook[skillName]
end

local function getScriptSkillBookMinLevel(scriptItem)
    if not scriptItem then return nil end
    local ok, level = pcall(function() return scriptItem:getLevelSkillTrained() end)
    if ok and tonumber(level) then return tonumber(level) end
    ok, level = pcall(function() return scriptItem:getLvlSkillTrained() end)
    if ok and tonumber(level) then return tonumber(level) end
    return nil
end

function LJ.captureSkillBooks(player)
    local result = {}
    local observable = {}
    if not player then return result, observable, false end
    local ok, allItems = pcall(function() return getScriptManager():getAllItems() end)
    if not ok or not allItems then return result, observable, false end

    for index = 0, allItems:size() - 1 do
        local scriptItem = allItems:get(index)
        if getSkillBookData(scriptItem) then
            local okType, fullType = pcall(function() return scriptItem:getFullName() end)
            if okType and fullType and tostring(fullType) ~= "" then
                fullType = tostring(fullType)
                observable[fullType] = true
                local okPages, pages = pcall(function()
                    return player:getAlreadyReadPages(fullType)
                end)
                if okPages and pages and tonumber(pages) and tonumber(pages) > 0 then
                    result[fullType] = tonumber(pages)
                end
            end
        end
    end
    return result, observable, true
end

local function hasPermanentMediaReward(codes)
    if not codes or tostring(codes) == "" then return false end
    for token in string.gmatch(tostring(codes), "[^,]+") do
        local code = string.match(token, "^%s*([A-Z][A-Z][A-Z])")
        if code and PERMANENT_MEDIA_CODES[code] then return true end
    end
    return false
end

function LJ.getPermanentRewardMedia()
    if LJ._permanentRewardMedia then return LJ._permanentRewardMedia end

    local result = { byId = {} }
    local ok, recordedMedia = pcall(function()
        return getZomboidRadio():getRecordedMedia()
    end)
    if not ok or not recordedMedia then return result end

    -- B42 type 0 is CD and type 1 is VHS. A stable media UUID plus a compact
    -- bit mask records exactly which permanent-reward lines were consumed.
    for mediaType = 0, 1 do
        local mediaList = recordedMedia:getAllMediaForType(mediaType)
        if mediaList then
            for mediaIndex = 0, mediaList:size() - 1 do
                local mediaData = mediaList:get(mediaIndex)
                local lineCount = mediaData and mediaData:getLineCount() or 0
                local rewardLines = {}
                local allLines = {}
                for lineIndex = 0, lineCount - 1 do
                    local line = mediaData:getLine(lineIndex)
                    local guid = line and line:getTextGuid() or nil
                    if guid and tostring(guid) ~= "" then
                        table.insert(allLines, tostring(guid))
                    end
                    local codesOk, codes = pcall(function() return line and line:getCodes() end)
                    if codesOk and hasPermanentMediaReward(codes) then
                        if guid and tostring(guid) ~= "" then
                            table.insert(rewardLines, tostring(guid))
                        end
                    end
                end

                if #rewardLines > 0 then
                    local idOk, mediaId = pcall(function() return mediaData:getId() end)
                    if idOk and mediaId and tostring(mediaId) ~= "" then
                        result.byId[tostring(mediaId)] = {
                            id = tostring(mediaId),
                            rewardLines = rewardLines,
                            allLines = allLines,
                        }
                    end
                end
            end
        end
    end

    LJ._permanentRewardMedia = result
    return result
end

local function hasMaskBit(mask, index)
    mask = math.max(0, math.floor(tonumber(mask) or 0))
    local bitValue = 2 ^ (index - 1)
    return math.floor(mask / bitValue) % 2 == 1
end

local function mergeMasks(left, right)
    left = math.max(0, math.floor(tonumber(left) or 0))
    right = math.max(0, math.floor(tonumber(right) or 0))
    local result = 0
    local bitValue = 1
    while left > 0 or right > 0 do
        if left % 2 == 1 or right % 2 == 1 then result = result + bitValue end
        left = math.floor(left / 2)
        right = math.floor(right / 2)
        bitValue = bitValue * 2
    end
    return result
end

local function countMissingMask(saved, current)
    saved = math.max(0, math.floor(tonumber(saved) or 0))
    current = math.max(0, math.floor(tonumber(current) or 0))
    local missing = 0
    while saved > 0 do
        if saved % 2 == 1 and current % 2 == 0 then missing = missing + 1 end
        saved = math.floor(saved / 2)
        current = math.floor(current / 2)
    end
    return missing
end

function LJ.captureKnownMediaRewards(player)
    local result = {}
    if not player then return result end

    for mediaId, media in pairs(LJ.getPermanentRewardMedia().byId) do
        local consumedReward = false
        for _, guid in ipairs(media.rewardLines) do
            local knownOk, known = pcall(function()
                return player:isKnownMediaLine(guid)
            end)
            if knownOk and known then
                consumedReward = true
                break
            end
        end
        -- A mixed entertainment/training recording is treated as one training
        -- item. Once any permanent reward was consumed, restore the whole tape
        -- through the game's native known-media-line state.
        if consumedReward then result[mediaId] = 1 end
    end
    return result
end

function LJ.getSavedSkills(item)
    if not LJ.isSupportedRecord(item) then return {} end
    return LJ.decodeSkills(item:getModData().LJ_skills)
end

function LJ.getSavedRecipes(item)
    if not LJ.isSupportedRecord(item) then return {} end
    return LJ.decodeRecipes(item:getModData().LJ_recipes)
end

function LJ.getSavedSkillBooks(item)
    if not LJ.isSupportedRecord(item) then return {} end
    return LJ.decodeSkills(item:getModData().LJ_skillBooks)
end

function LJ.getSavedSkillBookStates(item)
    if not LJ.isSupportedRecord(item) then return {}, false end
    local encoded = item:getModData().LJ_skillBookStates
    if encoded == nil then return {}, false end
    return LJ.decodeSkillBookStates(encoded), true
end

function LJ.getSavedMediaRewards(item)
    if not LJ.isSupportedRecord(item) then return {} end
    local saved = LJ.decodeSkills(item:getModData().LJ_mediaRewards)
    local eligible = LJ.getPermanentRewardMedia().byId
    local result = {}
    for mediaId, mask in pairs(saved) do
        if eligible[mediaId] and tonumber(mask) and tonumber(mask) > 0 then
            result[mediaId] = math.floor(tonumber(mask))
        end
    end
    return result
end

local function selectRecoverableEntries(source)
    local keys = {}
    for key, value in pairs(source or {}) do
        if value == true or (tonumber(value) and tonumber(value) > 0) then
            table.insert(keys, key)
        end
    end
    table.sort(keys)

    local selected = {}
    if #keys == 0 then return selected end
    local targetCount = math.min(#keys,
        math.max(1, math.ceil(#keys * LJ.getRecoveryRatio() - 0.000001)))
    for index = 1, targetCount do
        local key = keys[index]
        selected[key] = source[key]
    end
    return selected
end

function LJ.getRecoverableRecipes(item)
    return selectRecoverableEntries(LJ.getSavedRecipes(item))
end

function LJ.getRecoverableSkillBooks(item)
    return selectRecoverableEntries(LJ.getSavedSkillBooks(item))
end

function LJ.getRecoverableSkillBookStates(item, recoverableBooks)
    local savedStates, hasExactSnapshot = LJ.getSavedSkillBookStates(item)
    if not hasExactSnapshot then return {}, false end
    local result = {}
    for fullType in pairs(recoverableBooks or {}) do
        if savedStates[fullType] then result[fullType] = savedStates[fullType] end
    end
    return result, true
end

function LJ.getRecoverableMediaRewards(item)
    return selectRecoverableEntries(LJ.getSavedMediaRewards(item))
end

local function copyNumberMap(source)
    local result = {}
    for key, value in pairs(source or {}) do
        local number = tonumber(value)
        if number and number > 0 then result[key] = number end
    end
    return result
end

local function countNumberMapChanges(previous, current)
    local changed = 0
    local seen = {}
    for key, previousValue in pairs(previous or {}) do
        seen[key] = true
        if (tonumber(previousValue) or 0) ~= (tonumber(current[key]) or 0) then
            changed = changed + 1
        end
    end
    for key, currentValue in pairs(current or {}) do
        if not seen[key] and (tonumber(currentValue) or 0) > 0 then
            changed = changed + 1
        end
    end
    return changed
end

local function copySkillBookStates(source)
    local result = {}
    for fullType, state in pairs(source or {}) do
        if state then
            result[fullType] = {
                fullType = fullType,
                perkId = state.perkId,
                multiplier = state.multiplier,
                minLevel = state.minLevel,
                maxLevel = state.maxLevel,
            }
        end
    end
    return result
end

local function countSkillBookStateChanges(previous, current)
    local changed = 0
    local seen = {}
    for fullType, state in pairs(previous or {}) do
        seen[fullType] = true
        local other = current and current[fullType] or nil
        if LJ.encodeSkillBookStates({ [fullType] = state })
            ~= LJ.encodeSkillBookStates(other and { [fullType] = other } or {}) then
            changed = changed + 1
        end
    end
    for fullType, state in pairs(current or {}) do
        if not seen[fullType]
            and LJ.encodeSkillBookStates({ [fullType] = state }) ~= "" then
            changed = changed + 1
        end
    end
    return changed
end

local function mergeSkillBookSnapshot(savedBooks, currentBooks, observableBooks, captured)
    local mergedBooks = copyNumberMap(savedBooks)
    if not captured then return mergedBooks end

    -- A positive, currently observable page count is an intentional latest
    -- snapshot and may be lower than history. Missing entries are ambiguous:
    -- the mod/book may be unavailable or enumeration may be incomplete, so
    -- retain the previous record instead of silently erasing it.
    for fullType, pages in pairs(currentBooks or {}) do
        if observableBooks and observableBooks[fullType] then
            mergedBooks[fullType] = pages
        end
    end
    return mergedBooks
end

local function mergeSkillBookStateSnapshot(savedStates, currentStates, observableStates, captured)
    local merged = copySkillBookStates(savedStates)
    if not captured then return merged end
    -- A missing multiplier is not proof that the saved state disappeared.
    -- Multiplayer clients may not be able to observe it, so retain the saved
    -- state until a valid current state is available to replace it.
    for fullType, state in pairs(currentStates or {}) do
        merged[fullType] = state
    end
    return merged
end

function LJ.getSkillBookEntries(player, savedBooks)
    local entries = {}
    if not player then return entries end
    if CharacterTrait and CharacterTrait.ILLITERATE
        and player:hasTrait(CharacterTrait.ILLITERATE) then
        return entries
    end

    local fullTypes = {}
    for fullType, pages in pairs(savedBooks or {}) do
        if (tonumber(pages) or 0) > 0 then table.insert(fullTypes, fullType) end
    end
    table.sort(fullTypes)

    for _, fullType in ipairs(fullTypes) do
        local scriptItem = getScriptManager():FindItem(fullType)
        local skillBook = getSkillBookData(scriptItem)
        if skillBook and skillBook.perk then
            local minLevel = getScriptSkillBookMinLevel(scriptItem)
            local maxLevel = tonumber(scriptItem:getMaxLevelTrained())
            if minLevel and maxLevel then
                table.insert(entries, {
                    fullType = fullType,
                    pages = tonumber(savedBooks[fullType]) or 0,
                    scriptItem = scriptItem,
                    skillBook = skillBook,
                    minLevel = minLevel,
                    maxLevel = maxLevel,
                })
            end
        end
    end
    return entries
end

function LJ.getApplicableSkillBookEntries(player, savedBooks)
    local entries = {}
    for _, entry in ipairs(LJ.getSkillBookEntries(player, savedBooks)) do
        local nextLevel = player:getPerkLevel(entry.skillBook.perk) + 1
        if entry.minLevel <= nextLevel and nextLevel <= entry.maxLevel then
            table.insert(entries, entry)
        end
    end
    return entries
end

local function getBookMaxMultiplier(skillBook, level)
    if level == 1 then return skillBook.maxMultiplier1 end
    if level == 3 then return skillBook.maxMultiplier2 end
    if level == 5 then return skillBook.maxMultiplier3 end
    if level == 7 then return skillBook.maxMultiplier4 end
    if level == 9 then return skillBook.maxMultiplier5 end
    return nil
end

local function calculateSkillBookMultiplier(entry, pages)
    local pageCount = tonumber(entry.scriptItem:getNumberOfPages() or 0) or 0
    local maxMultiplier = getBookMaxMultiplier(entry.skillBook, entry.minLevel)
    if pageCount <= 0 or not maxMultiplier then return 0 end
    local readPercent = clamp(((tonumber(pages) or 0) / pageCount) * 100, 0, 100)
    return math.floor(readPercent / 10) * (maxMultiplier / 10)
end

local function getValidatedSkillBookState(entry, state)
    if not entry or not state then return nil end
    local perkId = getPerkId(entry.skillBook and entry.skillBook.perk)
    local multiplier = tonumber(state.multiplier)
    local minLevel = tonumber(state.minLevel)
    local maxLevel = tonumber(state.maxLevel)
    local configuredMaximum = getBookMaxMultiplier(entry.skillBook, entry.minLevel)
    if not perkId or tostring(state.perkId or "") ~= perkId
        or not isFiniteNumber(multiplier) or multiplier <= 0
        or not isFiniteNumber(minLevel) or minLevel ~= math.floor(minLevel)
        or not isFiniteNumber(maxLevel) or maxLevel ~= math.floor(maxLevel)
        or minLevel ~= entry.minLevel or maxLevel ~= entry.maxLevel
        or not configuredMaximum or multiplier > configuredMaximum then
        return nil
    end
    return {
        multiplier = multiplier,
        minLevel = minLevel,
        maxLevel = maxLevel,
    }
end

local function getActiveSkillBookMultiplier(xpObject, perk, nextLevel)
    if not xpObject then return 0 end
    local okMultiplier, multiplier = pcall(function() return xpObject:getMultiplier(perk) end)
    if okMultiplier and isFiniteNumber(multiplier) and multiplier > 0 then
        return multiplier
    end
    return 0
end

-- One target calculation for both the read gate and the actual restoration.
local function getSkillBookRestoreState(player, entry, savedStates, hasExactSnapshot)
    local pageCount = tonumber(entry.scriptItem:getNumberOfPages() or 0) or 0
    if pageCount <= 0 then return nil end
    local targetPages = clamp(entry.pages, 0, pageCount)
    local currentPages = tonumber(player:getAlreadyReadPages(entry.fullType) or 0) or 0
    local result = { targetPages = targetPages, currentPages = currentPages }
    local xpObject = player:getXp()
    local nextLevel = player:getPerkLevel(entry.skillBook.perk) + 1
    if xpObject and entry.minLevel <= nextLevel and nextLevel <= entry.maxLevel then
        local savedState = getValidatedSkillBookState(entry,
            savedStates and savedStates[entry.fullType] or nil)
        result.multiplier = hasExactSnapshot
            and (savedState and savedState.multiplier or 0)
            or calculateSkillBookMultiplier(entry, math.max(currentPages, targetPages))
        result.minLevel = savedState and savedState.minLevel or entry.minLevel
        result.maxLevel = savedState and savedState.maxLevel or entry.maxLevel
        result.missingMultiplier = normalizeStoredSkillBookMultiplier(result.multiplier)
            > normalizeStoredSkillBookMultiplier(getActiveSkillBookMultiplier(
                xpObject, entry.skillBook.perk, nextLevel))
    end
    return result
end

function LJ.hasSkillBookMultiplierTarget(player, item, onlyMissing)
    if not LJ.isSkillBooksEnabled() then return false end
    local books = LJ.getRecoverableSkillBooks(item)
    local states, exact = LJ.getRecoverableSkillBookStates(item, books)
    for _, entry in ipairs(LJ.getSkillBookEntries(player, books)) do
        local restore = getSkillBookRestoreState(player, entry, states, exact)
        if restore and (restore.multiplier or 0) > 0
            and (not onlyMissing or restore.missingMultiplier) then return true end
    end
    return false
end

local function resolveSavedPerk(perkId)
    local perk = PerkFactory.Perks.FromString(perkId)
    if perk and perk ~= PerkFactory.Perks.None then return perk end
    return nil
end

function LJ.captureSkillBookStates(player, books)
    local result = {}
    local observable = {}
    if not player or not player:getXp() then return result, observable, false end

    local xpObject = player:getXp()
    for _, entry in ipairs(LJ.getApplicableSkillBookEntries(player, books)) do
        observable[entry.fullType] = true
        local okMultiplier, multiplier = pcall(function()
            return xpObject:getMultiplier(entry.skillBook.perk)
        end)
        local perkId = getPerkId(entry.skillBook.perk)
        if okMultiplier and perkId and isFiniteNumber(multiplier) and multiplier > 0 then
            result[entry.fullType] = {
                fullType = entry.fullType,
                perkId = perkId,
                multiplier = multiplier,
                minLevel = entry.minLevel,
                maxLevel = entry.maxLevel,
            }
        end
    end
    return result, observable, true
end

function LJ.getWriteDelta(player, item)
    local savedSkills = LJ.getSavedSkills(item)
    local savedRecipes = LJ.getSavedRecipes(item)
    local savedBooks = LJ.getSavedSkillBooks(item)
    local savedBookStates = LJ.getSavedSkillBookStates(item)
    local savedMedia = LJ.getSavedMediaRewards(item)
    local mergedSkills = {}
    local mergedRecipes = {}
    local mergedBooks = {}
    local mergedBookStates = {}
    local mergedMedia = {}
    local deltaXp = 0
    local changedSkills = 0
    local newRecipes = 0
    local changedBooks = 0
    local newMediaRewards = 0

    for perkId, savedXp in pairs(savedSkills) do mergedSkills[perkId] = savedXp end
    for recipeName, known in pairs(savedRecipes) do if known then mergedRecipes[recipeName] = true end end
    for fullType, pages in pairs(savedBooks) do mergedBooks[fullType] = pages end
    mergedBookStates = copySkillBookStates(savedBookStates)
    for mediaId, mask in pairs(savedMedia) do mergedMedia[mediaId] = mask end

    if LJ.isSkillXpEnabled() then
        for perkId, currentXp in pairs(LJ.captureSkills(player)) do
            local savedXp = tonumber(savedSkills[perkId] or 0) or 0
            local currentValue = tonumber(currentXp or 0) or 0
            if normalizeStoredSkillXp(currentValue) > normalizeStoredSkillXp(savedXp) then
                deltaXp = deltaXp + (currentValue - savedXp)
                changedSkills = changedSkills + 1
                mergedSkills[perkId] = currentValue
            elseif mergedSkills[perkId] == nil then
                mergedSkills[perkId] = currentValue
            end
        end
    end

    if LJ.isRecipesEnabled() then
        for recipeName, known in pairs(LJ.captureRecipes(player)) do
            if known then
                if not savedRecipes[recipeName] then newRecipes = newRecipes + 1 end
                mergedRecipes[recipeName] = true
            end
        end
    end

    if LJ.isSkillBooksEnabled() then
        local currentBooks, observableBooks, captured = LJ.captureSkillBooks(player)
        mergedBooks = mergeSkillBookSnapshot(savedBooks, currentBooks, observableBooks, captured)
        changedBooks = countNumberMapChanges(savedBooks, mergedBooks)
        if captured then
            local currentStates, observableStates, statesCaptured =
                LJ.captureSkillBookStates(player, currentBooks)
            mergedBookStates = mergeSkillBookStateSnapshot(savedBookStates,
                currentStates, observableStates, statesCaptured)
            changedBooks = changedBooks
                + countSkillBookStateChanges(savedBookStates, mergedBookStates)
        end
    end

    if LJ.isTrainingMediaEnabled() then
        for mediaId, currentMask in pairs(LJ.captureKnownMediaRewards(player)) do
            local savedMask = tonumber(savedMedia[mediaId] or 0) or 0
            newMediaRewards = newMediaRewards
                + countMissingMask(currentMask, savedMask)
            mergedMedia[mediaId] = mergeMasks(savedMask, currentMask)
        end
    end

    return {
        xp = deltaXp,
        skills = changedSkills,
        recipes = newRecipes,
        books = changedBooks,
        vhs = newMediaRewards,
        mergedSkills = mergedSkills,
        mergedRecipes = mergedRecipes,
        mergedBooks = mergedBooks,
        mergedBookStates = mergedBookStates,
        mergedMedia = mergedMedia,
    }
end

function LJ.getReadDelta(player, item)
    local missingXp = 0
    local changedSkills = 0
    local missingRecipes = 0
    local missingBooks = 0
    local missingVhsLines = 0

    if LJ.isSkillXpEnabled() then
        local currentSkills = LJ.captureSkills(player)
        for perkId, targetXp in pairs(LJ.getSavedSkills(item)) do
            local currentXp = tonumber(currentSkills[perkId] or 0) or 0
            local targetValue = LJ.getRecoverableSkillXp(targetXp)
            if resolveSavedPerk(perkId)
                and normalizeStoredSkillXp(targetValue) > normalizeStoredSkillXp(currentXp) then
                missingXp = missingXp + (targetValue - currentXp)
                changedSkills = changedSkills + 1
            end
        end
    end

    if LJ.isRecipesEnabled() then
        local currentRecipes = LJ.captureRecipes(player)
        for recipeName, known in pairs(LJ.getRecoverableRecipes(item)) do
            if known and not currentRecipes[recipeName] then missingRecipes = missingRecipes + 1 end
        end
    end

    if LJ.isSkillBooksEnabled() then
        local savedBooks = LJ.getRecoverableSkillBooks(item)
        for _, entry in ipairs(LJ.getSkillBookEntries(player, savedBooks)) do
            local currentPages = tonumber(player:getAlreadyReadPages(entry.fullType) or 0) or 0
            local targetPages = clamp(entry.pages, 0, entry.scriptItem:getNumberOfPages())
            -- The client cannot reliably observe multiplayer XP multipliers.
            -- Keep ordinary workload based on pages. A multiplier-only repair
            -- is admitted separately by authority (MP uses readStatus).
            if targetPages > currentPages then
                missingBooks = missingBooks + 1
            end
        end
    end

    if LJ.isTrainingMediaEnabled() then
        local mediaIndex = LJ.getPermanentRewardMedia().byId
        for mediaId in pairs(LJ.getRecoverableMediaRewards(item)) do
            local media = mediaIndex[mediaId]
            if media then
                for _, guid in ipairs(media.allLines or media.rewardLines) do
                    if not player:isKnownMediaLine(guid) then
                        missingVhsLines = missingVhsLines + 1
                    end
                end
            end
        end
    end

    local delta = {
        xp = missingXp,
        skills = changedSkills,
        recipes = missingRecipes,
        books = missingBooks,
        vhs = missingVhsLines,
    }
    -- MP clients cannot infer a deficit from an unobservable multiplier.
    -- A pure repair uses the unchanged base reading workload on both sides.
    if not LJ.hasDelta(delta) and not isClient()
        and LJ.hasSkillBookMultiplierTarget(player, item, true) then
        delta.multiplierRepair = true
    end
    return delta
end

function LJ.hasDelta(delta)
    if not delta then return false end
    return (tonumber(delta.xp or 0) or 0) > 0
        or delta.multiplierRepair == true
        or (tonumber(delta.skills or 0) or 0) > 0
        or (tonumber(delta.recipes or 0) or 0) > 0
        or (tonumber(delta.books or 0) or 0) > 0
        or (tonumber(delta.vhs or 0) or 0) > 0
end

function LJ.getActionActorKey(player)
    local identity = LJ.getCharacterIdentity(player)
    return table.concat({
        tostring(identity.username or ""),
        tostring(identity.descId or ""),
        tostring(identity.name or ""),
    }, "\31")
end

function LJ.getActionSignature(action, item, delta)
    delta = delta or {}
    local counts = table.concat({
        tostring(tonumber(delta.xp or 0) or 0),
        tostring(tonumber(delta.skills or 0) or 0),
        tostring(tonumber(delta.recipes or 0) or 0),
        tostring(tonumber(delta.books or 0) or 0),
        tostring(tonumber(delta.vhs or 0) or 0),
    }, "|")
    if delta.multiplierRepair == true then counts = counts .. "|multiplier-repair" end

    if action == "write" then
        return table.concat({
            counts,
            LJ.encodeSkills(delta.mergedSkills),
            LJ.encodeRecipes(delta.mergedRecipes),
            LJ.encodeSkills(delta.mergedBooks),
            LJ.encodeSkillBookStates(delta.mergedBookStates),
            LJ.encodeSkills(delta.mergedMedia),
        }, "\30")
    end

    local md = item and item:getModData() or {}
    return table.concat({
        counts,
        tostring(md.LJ_version or ""),
        tostring(md.LJ_skills or ""),
        tostring(md.LJ_recipes or ""),
        tostring(md.LJ_skillBooks or ""),
        tostring(md.LJ_skillBookStates or ""),
        tostring(md.LJ_mediaRewards or ""),
    }, "\30")
end

function LJ.getSavedActionPage(item, action, signature, actorKey, totalPages)
    if not item then return 0 end
    local md = item:getModData()
    if tostring(md.LJ_progressAction or "") ~= tostring(action or "")
        or tostring(md.LJ_progressActor or "") ~= tostring(actorKey or "") then
        return 0
    end
    totalPages = math.max(1, math.floor(tonumber(totalPages)
        or LJ.DEFAULT_ACTION_PROGRESS_PAGES))
    local savedPage = math.max(0, math.floor(tonumber(md.LJ_progressPage) or 0))
    local savedModelVersion = tonumber(md.LJ_progressModelVersion)

    -- 1.01 checkpoints predate the explicit progress model. Preserve their
    -- completed proportion when the 1.02 page-rate formula changes the total.
    -- Unknown explicit versions are not guessed.
    if savedModelVersion == nil then
        local savedTotalPages = math.max(0,
            math.floor(tonumber(md.LJ_progressTotalPages) or 0))
        if savedTotalPages > 0 then
            return clamp(math.floor(savedPage * totalPages / savedTotalPages),
                0, totalPages)
        end
    elseif savedModelVersion ~= LJ.ACTION_PROGRESS_MODEL_VERSION then
        return 0
    end

    -- Knowledge can change between interruptions (even passive XP is enough
    -- to change the snapshot signature). Preserve work already completed on
    -- the same item by the same actor and clamp it to the newly calculated
    -- page count. The current signature is still saved below and remains a
    -- strict requirement for committing an active server token.
    return clamp(savedPage, 0, totalPages)
end

function LJ.saveActionProgress(item, action, signature, actorKey, page, totalPages)
    if not item then return false end
    totalPages = math.max(1, math.floor(tonumber(totalPages)
        or LJ.DEFAULT_ACTION_PROGRESS_PAGES))
    page = clamp(math.floor(tonumber(page) or 0), 0, totalPages)
    local md = item:getModData()
    md.LJ_progressAction = tostring(action or "")
    md.LJ_progressSignature = tostring(signature or "")
    md.LJ_progressActor = tostring(actorKey or "")
    md.LJ_progressPage = page
    md.LJ_progressTotalPages = totalPages
    md.LJ_progressModelVersion = LJ.ACTION_PROGRESS_MODEL_VERSION
    return true
end

function LJ.clearActionProgress(item)
    if not item then return end
    local md = item:getModData()
    md.LJ_progressAction = nil
    md.LJ_progressSignature = nil
    md.LJ_progressActor = nil
    md.LJ_progressPage = nil
    md.LJ_progressTotalPages = nil
    md.LJ_progressModelVersion = nil
end

function LJ.getRemainingActionTime(totalTime, startPage, totalPages)
    totalPages = math.max(1, math.floor(tonumber(totalPages)
        or LJ.DEFAULT_ACTION_PROGRESS_PAGES))
    startPage = clamp(math.floor(tonumber(startPage) or 0), 0, totalPages)
    local remainingRatio = (totalPages - startPage) / totalPages
    return math.max(1, math.floor((tonumber(totalTime) or 1) * remainingRatio))
end

local function getVanillaReadingTime(pageCount)
    local minutesPerPage = 2.0
    local okOption, configured = pcall(function()
        local option = getSandboxOptions():getOptionByName("MinutesPerPage")
        return option and option:getValue() or nil
    end)
    if okOption and tonumber(configured) and tonumber(configured) >= 0 then
        minutesPerPage = tonumber(configured)
    end

    local minutesPerDay = 30
    local okTime, configuredDay = pcall(function()
        local gameTime = getGameTime()
        return gameTime and gameTime:getMinutesPerDay() or nil
    end)
    if okTime and tonumber(configuredDay) and tonumber(configuredDay) > 0 then
        minutesPerDay = tonumber(configuredDay)
    end

    -- ISReadABook uses pages * MinutesPerPage / (1 / MinutesPerDay / 2).
    return math.max(1, pageCount * minutesPerPage * minutesPerDay * 2)
end

function LJ.getPagesForContentUnits(units)
    return math.max(1, math.ceil(math.max(0, tonumber(units) or 0)
        * LJ.ACTION_PAGE_RATE_NUMERATOR / LJ.ACTION_PAGE_RATE_DENOMINATOR))
end

function LJ.getActionPageCount(action, delta)
    delta = delta or {}
    local xpBlocks = math.ceil(math.max(0, tonumber(delta.xp or 0) or 0) / 100)
    local units
    if action == "read" then
        units = LJ.READ_BASE
            + ((tonumber(delta.skills or 0) or 0) * LJ.READ_PER_CHANGED_SKILL)
            + (xpBlocks * LJ.READ_PER_100_XP)
            + ((tonumber(delta.recipes or 0) or 0) * LJ.READ_PER_NEW_RECIPE)
            + ((tonumber(delta.books or 0) or 0) * LJ.READ_PER_SKILL_BOOK)
            + ((tonumber(delta.vhs or 0) or 0) * LJ.READ_PER_VHS_LINE)
    else
        units = LJ.WRITE_BASE
            + ((tonumber(delta.skills or 0) or 0) * LJ.WRITE_PER_CHANGED_SKILL)
            + (xpBlocks * LJ.WRITE_PER_100_XP)
            + ((tonumber(delta.recipes or 0) or 0) * LJ.WRITE_PER_NEW_RECIPE)
            + ((tonumber(delta.books or 0) or 0) * LJ.WRITE_PER_SKILL_BOOK)
            + ((tonumber(delta.vhs or 0) or 0) * LJ.WRITE_PER_VHS_LINE)
    end
    return LJ.getPagesForContentUnits(units)
end

function LJ.getWriteTime(delta, player)
    if LJ.FIXED_TEST_ACTION_TIME then return LJ.FIXED_TEST_ACTION_TIME end
    if player and player:isTimedActionInstant() then return 1 end
    local time = getVanillaReadingTime(LJ.getActionPageCount("write", delta))
    time = time * LJ.getActionTimeMultiplier("write", player)
    return math.max(1, math.floor(time))
end

function LJ.getReadTime(delta, player)
    if LJ.FIXED_TEST_ACTION_TIME then return LJ.FIXED_TEST_ACTION_TIME end
    require "TimedActions/ISReadABook"
    if player:isTimedActionInstant() then return 1 end
    local pages = LJ.getActionPageCount("read", delta)
    -- A Lua-only workload view for the vanilla duration calculation. Never
    -- change the real Diary's page counters or invoke literature completion.
    -- checkLevel returns immediately for a non-skill book; setters below only
    -- affect this disposable view, not player or journal state.
    local view = {
        getNumberOfPages = function() return pages end,
        getSkillTrained = function() return nil end,
        getFullType = function() return "Base.Diary1" end,
        setAlreadyReadPages = function() end,
        getAlreadyReadPages = function() return 0 end,
        hasTag = function() return false end,
    }
    local minutes = getSandboxOptions():getOptionByName("MinutesPerPage"):getValue() or 2
    if minutes < 0 then minutes = 2 end
    local time = ISReadABook.getDuration({
        character = player, item = view, minutesPerPage = minutes,
    })
    time = time * LJ.getActionTimeMultiplier("read", player)
    return math.max(1, math.floor(time))
end

function LJ.isActionContextValid(player, item, kind)
    if not player or player:isDead() or not LJ.isSupportedItem(item) then return false end
    if LJ.findItemById(player, item:getID()) ~= item then return false end
    if player:tooDarkToRead() or player:hasTrait(CharacterTrait.ILLITERATE) then return false end
    local vehicle = player:getVehicle()
    if vehicle and vehicle:isDriver(player) and vehicle:isEngineRunning()
        and vehicle:getSpeed2D() ~= 0 then return false end
    if kind == "write" then return LJ.canCurrentCharacterUpdate(player, item) end
    if kind == "read" then return LJ.isAuthor(player, item) end
    return false
end

-- Snapshot/tool work is restricted to transaction boundaries, never the
-- timed action's per-frame validity callback.
function LJ.canPerformAction(player, item, kind)
    if not LJ.isActionContextValid(player, item, kind) then return false end
    if kind == "write" then
        return LJ.hasWritingTool(player)
            and LJ.hasDelta(LJ.getWriteDelta(player, item))
    elseif kind == "read" then
        return LJ.hasDelta(LJ.getReadDelta(player, item))
    end
    return false
end

function LJ.commitWrite(player, item)
    if not player or not LJ.isSupportedItem(item) then return false end
    if LJ.isWritten(item) and not LJ.migrateRecord(item) then return false end
    if not LJ.hasWritingTool(player) then return false end
    if not LJ.canCurrentCharacterUpdate(player, item) then return false end
    local delta = LJ.getWriteDelta(player, item)
    if not LJ.hasDelta(delta) then return false end

    local identity = LJ.getCharacterIdentity(player)
    local md = item:getModData()
    md.LJ_version = LJ.VERSION
    md.LJ_written = true
    if not md.LJ_authorName or tostring(md.LJ_authorName) == "" then
        md.LJ_authorName = identity.name
        md.LJ_authorUser = identity.username
        md.LJ_authorDescId = identity.descId
    end
    local writtenAt = LJ.getGameDateTimeStamp()
    if writtenAt then md.LJ_writtenAt = writtenAt end
    md.LJ_skills = LJ.encodeSkills(delta.mergedSkills)
    md.LJ_recipes = LJ.encodeRecipes(delta.mergedRecipes)
    md.LJ_skillBooks = LJ.encodeSkills(delta.mergedBooks)
    md.LJ_skillBookStates = LJ.encodeSkillBookStates(delta.mergedBookStates)
    md.LJ_skillBookMultipliers = nil
    md.LJ_mediaRewards = LJ.encodeSkills(delta.mergedMedia)
    md.LJ_mediaRewardMode = "whole-media"
    LJ.clearActionProgress(item)
    LJ.refreshJournalPresentation(item)
    return true
end

function LJ.applySkillBookProgress(player, savedBooks, savedStates, hasExactSnapshot)
    local changed = false
    for _, entry in ipairs(LJ.getSkillBookEntries(player, savedBooks)) do
        local restore = getSkillBookRestoreState(player, entry, savedStates, hasExactSnapshot)
        if restore then
            if restore.targetPages > restore.currentPages then
                player:setAlreadyReadPages(entry.fullType, restore.targetPages)
                changed = true
            end
            if restore.missingMultiplier then
                addXpMultiplier(player, entry.skillBook.perk, restore.multiplier,
                    restore.minLevel, restore.maxLevel)
                changed = true
            end
        end
    end
    return changed
end

function LJ.getMissingReadFields(player, item)
    local result = {
        recipes = {},
        mediaLines = {},
        skillBooks = "",
        skillBookStates = "",
        hasExactSkillBookSnapshot = false,
    }
    if not player or not LJ.isWritten(item) or not LJ.migrateRecord(item) then
        return result
    end

    if LJ.isRecipesEnabled() then
        local currentRecipes = LJ.captureRecipes(player)
        for recipeName, known in pairs(LJ.getRecoverableRecipes(item)) do
            if known and not currentRecipes[recipeName] then
                table.insert(result.recipes, recipeName)
            end
        end
        table.sort(result.recipes)
    end

    if LJ.isSkillBooksEnabled() then
        local savedBooks = LJ.getRecoverableSkillBooks(item)
        local savedBookStates, hasExactSnapshot =
            LJ.getRecoverableSkillBookStates(item, savedBooks)
        result.skillBooks = LJ.encodeSkills(savedBooks)
        result.skillBookStates = LJ.encodeSkillBookStates(savedBookStates)
        result.hasExactSkillBookSnapshot = hasExactSnapshot
    end

    if LJ.isTrainingMediaEnabled() then
        local seenMediaLines = {}
        local mediaIndex = LJ.getPermanentRewardMedia().byId
        for mediaId in pairs(LJ.getRecoverableMediaRewards(item)) do
            local media = mediaIndex[mediaId]
            if media then
                for _, guid in ipairs(media.allLines or media.rewardLines) do
                    if not seenMediaLines[guid]
                        and not player:isKnownMediaLine(guid) then
                        seenMediaLines[guid] = true
                        table.insert(result.mediaLines, guid)
                    end
                end
            end
        end
    end
    table.sort(result.mediaLines)
    return result
end

function LJ.applyRead(player, item)
    if not player or not LJ.isWritten(item) or not LJ.migrateRecord(item) then return false end
    if not LJ.isAuthor(player, item) then return false end
    local changed = false
    local needsPlayerFieldSync = false

    if LJ.isSkillXpEnabled() then
        local xpObject = player:getXp()
        for perkId, targetXp in pairs(LJ.getSavedSkills(item)) do
            local perk = resolveSavedPerk(perkId)
            if perk then
                local currentXp = xpObject:getXP(perk)
                local targetValue = LJ.getRecoverableSkillXp(targetXp)
                if targetValue > currentXp then
                    addXpNoMultiplier(player, perk, targetValue - currentXp)
                    changed = true
                end
            end
        end
    end

    local missingFields = LJ.getMissingReadFields(player, item)

    for _, recipeName in ipairs(missingFields.recipes) do
        player:learnRecipe(recipeName)
        changed = true
        needsPlayerFieldSync = true
    end

    if LJ.isSkillBooksEnabled() then
        local savedBooks = LJ.getRecoverableSkillBooks(item)
        local savedBookStates, hasExactSnapshot =
            LJ.getRecoverableSkillBookStates(item, savedBooks)
        if LJ.applySkillBookProgress(player, savedBooks,
                savedBookStates, hasExactSnapshot) then
            changed = true
            needsPlayerFieldSync = true
        end
    end

    for _, guid in ipairs(missingFields.mediaLines) do
        player:addKnownMediaLine(guid)
        changed = true
    end

    -- addXpNoMultiplier uses the native XP path. This is the vanilla field
    -- synchronization used by book reading for recipes and read-page state.
    if needsPlayerFieldSync and isServer() and sendSyncPlayerFields then
        sendSyncPlayerFields(player, 0x00000007)
    end
    if changed then LJ.clearActionProgress(item) end
    return changed, missingFields
end

function LJ.findItemById(player, itemId)
    if not player or itemId == nil then return nil end
    local inventory = player:getInventory()
    if not inventory then return nil end
    local id = tonumber(itemId)
    if not id then return nil end
    local ok, item = pcall(function()
        return inventory:getItemWithIDRecursiv(id)
    end)
    if ok then return item end
    return nil
end

return LJ
end

SurvivorsSong = SurvivorsSong or {}
SurvivorsSong.newJournalCore = create
return create
