-- Generated by mods/survivors-song/tools/generate_journal_core.py; do not edit.
-- Source: Personal Journal 1.3.3-release
-- Repository: https://github.com/Kinkairy/Project-Zomboid-Personal-Journal
-- Git commit: 718e68cde288d8e1c6eddda501b83f083f723392
-- Copyright (c) 2026 Kinkairy; MIT License, see JOURNAL-LICENSE.txt.
-- Source file: workshop/Contents/mods/LegacyJournal/42.20/media/lua/shared/legacyjournal/legacyjournal_skillbook_compat.lua
-- Source SHA-256: bdc2fb9ebf4d6c2d7f41b62ae327b3e4691a6e53fdcb0136adddbdc8d06a6931

require "TimedActions/ISReadABook"

-- B42's instant timed-action path can complete a skill book without copying
-- its final page count to the character. Use the same vanilla setter before
-- the original completion routine sends the player and item field syncs.
local version = tostring(getCore():getVersionNumber()):match("^(%d+%.%d+%.%d+)")
-- The unchanged native completion defect is also reproduced on 42.21.0.
local verifiedVersion = version == "42.20.4" or version == "42.21.0"
if verifiedVersion and ISReadABook and not ISReadABook._legacyJournalInstantPageFix then
    local vanillaComplete = ISReadABook.complete

    function ISReadABook:complete()
        if self.character and self.item
            and not self.forceStopped
            and self.character:isTimedActionInstant() then
            local skill = self.item:getSkillTrained()
            local pages = tonumber(self.item:getNumberOfPages() or 0) or 0
            if skill and SkillBook[skill] and pages > 0
                and self.character:getAlreadyReadPages(self.item:getFullType()) < pages then
                self.character:setAlreadyReadPages(self.item:getFullType(), pages)
            end
        end
        return vanillaComplete(self)
    end

    ISReadABook._legacyJournalInstantPageFix = true
end

print("[LegacyJournal] instant skill-book page compatibility loaded")
